# Generated by Django 3.2.12 on 2024-05-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nama_barang', models.CharField(blank=True, max_length=255, null=True)),
                ('stok', models.IntegerField(blank=True, default=0, null=True)),
                ('jumlah_terjual', models.IntegerField(blank=True, default=0, null=True)),
                ('jenis_barang', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('jumlah', models.IntegerField(blank=True, default=0, null=True)),
                ('jenis_transaksi', models.CharField(blank=True, max_length=255, null=True)),
                ('barang', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barangs', to='backend.barang')),
            ],
        ),
    ]
