# Generated by Django 3.2.12 on 2024-05-07 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangs', to='backend.barang'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
